### ISSUE TITLE
Error: the request entity is too large

### ISSUE THREAD

**Issue by mojoaxel** [npm/npm-fullfat-registry#18]
Copying from replicate.npmjs.com results in an `too_large` error:
```
ohnoes! errorz! { [Error: {"error":"too_large","reason":"the request entity is too large"}
```
Who throws this error? 
Is there anything that could be done to handle this better?

**Comment by asaf400** [comment]
Hello mojoaxel,

I am a fellow replicator, and I've stumbled upon the same error just a few days ago as well..
Since the error is a generic http status 413 code, It was challenging to find the culprit, although luckily for you, I have found it...

It's the CouchDB http server responding with 413..

Using the Following Resources:
http://docs.couchdb.org/en/2.1.1/config/http.html#httpd/max_http_request_size
http://docs.couchdb.org/en/2.1.1/config/couchdb.html#couchdb/max_document_size

I was able to overcome the issue, raising the defaults to 4GB for both values.. (4294967296 bytes)
in /opt/couchdb/etc/default.ini

**Comment by mojoaxel** [comment]
Thx @asaf400

**Comment by mojoaxel** [comment]
@asaf400 Maybe you can help answering this question, also? 😉 
https://stackoverflow.com/questions/48115457/how-to-create-an-offline-mirror-of-the-npm-registry

**Comment by asaf400** [comment]
Well, I do not know how large the npm is, But I'm downloading all of it
anyways..
Although using this repository, I am now stuck on specific set of packages
\ update sequence  - after about 80GB of data..

It may be a result of poor coding, or just an unstable internet causing
connection drops during download, Once I have it all, I'll try and update
you..

So far this repo contains the only known method for replicating it in an
'official way'...
You may want to have an alternative self-written script which parses all
the package names, and then for each, parse & download all the tgz's of
each version..

2018-01-09 15:34 GMT+02:00 Alexander Wunschik <notifications@github.com>:

**Comment by asaf400** [comment]
As promised in my last comment,

I am having issues replicating change 'actor-sdk-357997' and it's attachments...

**Comment by sigsegv13** [comment]
@asaf400 I ran into an issue replicating 'actor-sdk' as well.  My couchdb request size was set to 4GB when it initially failed, ratcheted that up to 8GB... no joy... then up to 16GB before it finally replicated.  Didn't bother to find out whether a value somewhere between 8GB and 16GB would have worked.

For reference and anyone that's interested, here is the error thrown:
-> actor-sdk-1.0.385.tgz
ERROR { Error: {"error":"too_large","reason":"the request entity is too large"}

    at IncomingMessage.<anonymous> (/data/npm-fullfat-registry/node_modules/parse-json-response/parse.js:38:12)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9) statusCode: 413 }
/data/npm-fullfat-registry/node_modules/npm-fullfat-registry/bin/fullfat.js:80
  throw er
  ^

Error: {"error":"too_large","reason":"the request entity is too large"}

    at IncomingMessage.<anonymous> (/data/npm-fullfat-registry/node_modules/parse-json-response/parse.js:38:12)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
fullfat.js crashed with exit code 1. Respawning
START npm FullFat/1.1.4 node/v6.14.0 pid=23413
357997: actor-sdk

**Comment by asaf400** [comment]
Thanks for writing that info down here 😀

I'll use that limit next time I'll attempt a full sync (abounded my
previous effort)
